name: 28589 - Deploy Docker image

on:
  workflow_run:
    workflows: ["28589 - Testiranje C++ kode"]  # TOČNO tako kot v testnem .yml
    types:
      - completed

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    name: Deploy na DockerHub

    steps:
      - name: Kloniraj repozitorij
        uses: actions/checkout@v3

      - name: Prijava v DockerHub
        run: echo "${{ secrets.DOCKERHUB_PASSWORD }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

      - name: Zgradi Docker image
        run: docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/domaca-naloga:latest .

      - name: Potisni Docker image na DockerHub
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/domaca-naloga:latest
